# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spectral <- function(DF, CnMIN = 1L, TOL = 0.00001, names = 1L, verbose = 0L) {
    .Call('_rSpectral_spectral', PACKAGE = 'rSpectral', DF, CnMIN, TOL, names, verbose)
}

